/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import datos.ClienteDAO;
import datos.ReservacionDAO;
import dominio.Cliente;
import dominio.Reservacion;
import java.awt.Color;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    DefaultTableModel modelo;

    public Cliente clienteActual;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Principal(Cliente cliente) {
        System.out.println("XDDDD");
        initComponents();
        this.setLocationRelativeTo(null);
        clienteActual = cliente;

        lblCliente.setText(clienteActual.getNombre());
        ActualizarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        persona = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        cantPersonas = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        comentario = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        M1 = new javax.swing.JRadioButton();
        M2 = new javax.swing.JRadioButton();
        M3 = new javax.swing.JRadioButton();
        M4 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Calendario = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        id_eliminar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(204, 255, 0));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(200, 200));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Buscar Disponibilidad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad Personas");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("FECHA A RESERVAR");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("N. De Mesa");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));
        jPanel2.add(persona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("DNI");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        jPanel2.add(dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 210, -1));
        jPanel2.add(cantPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jButton2.setText("RESERVAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 190, 50));

        jLabel4.setText("Comentarios");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        comentario.setColumns(20);
        comentario.setRows(5);
        jScrollPane1.setViewportView(comentario);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 290, 270));

        jLabel8.setText("Bienvenido: ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblCliente.setText("Usuario");
        jPanel2.add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        buttonGroup1.add(M1);
        M1.setText("1");
        jPanel2.add(M1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        buttonGroup1.add(M2);
        M2.setText("2");
        jPanel2.add(M2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        M3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(M3);
        M3.setText("3");
        jPanel2.add(M3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        buttonGroup1.add(M4);
        M4.setText("4");
        jPanel2.add(M4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Persona a Nombre de la Reserva");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/EmpresaBrand.jpg"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));
        jPanel2.add(Calendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 150, -1));

        jTabbedPane1.addTab("Reservar", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("CANCELACION DE RESERVA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 320, 210));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("ID");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 40, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Telefono", "Fecha Alquiler", "Mesa", "Persona", "DNI", "Personas", "Comentario", "ID"
            }
        ));
        jScrollPane3.setViewportView(tabla);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 730, 100));

        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 120, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Razon de la Cancelacion");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        jPanel1.add(id_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 40, -1));
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        jTabbedPane1.addTab("Registrar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //----------------------BUSCAR DISPONIBILIDAD-----------------------------
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        java.util.Date mFecha = Calendario.getDate();
        if (mFecha == null) {
            JOptionPane.showMessageDialog(null, "INGRESA DATOS");
            return;
        }
        long fecha = mFecha.getTime();

        Date fecha_sql = new Date(fecha);

        String fecha_Final = fecha_sql.toString();
//        JOptionPane.showMessageDialog(null, ));

        String[] partes = fecha_Final.split("-");

        int anio = Integer.parseInt(partes[0]);
        int mes = Integer.parseInt(partes[1]);
        int dia = Integer.parseInt(partes[2]);
        


        ReservacionDAO conexionReserva = new ReservacionDAO();
        List<Reservacion> lista_reservas = conexionReserva.mostrar();

        //Activando campos
        M1.setEnabled(true);
        M2.setEnabled(true);
        M3.setEnabled(true);
        M4.setEnabled(true);

        buttonGroup1.clearSelection();
        if (lista_reservas.size() == 0) {
            JOptionPane.showMessageDialog(null, "AUN NO HAY RESERVAS");
            return;
        }
        int mesas_vacias = 0;
        for (int i = 0; i < lista_reservas.size(); i++) {
            if (fecha_Final.equals((new SimpleDateFormat("yyyy-MM-dd").format(lista_reservas.get(i).getFecha())))) {
                //VIENDO QUE MESAS NO ESTAN DISPONIBLES
                int idx = lista_reservas.get(i).getMesa();

                if (idx == 1) {
                    M1.setEnabled(false);
                    mesas_vacias = 1;
                }
                if (idx == 2) {
                    M2.setEnabled(false);
                    mesas_vacias = 1;
                }
                if (idx == 3) {
                    M3.setEnabled(false);
                    mesas_vacias = 1;
                }
                if (idx == 4) {
                    M4.setEnabled(false);
                    mesas_vacias = 1;
                }

            }
        }

        if (mesas_vacias == 0) {
            JOptionPane.showMessageDialog(null, "MESAS DISPONIBLES");
        } else if (mesas_vacias == 1) {
            JOptionPane.showMessageDialog(null, "AUN QUEDAN MESAS DISPONIBLES");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ReservacionDAO conexionAReservacion = new ReservacionDAO();

        
        java.util.Date mFecha = Calendario.getDate();
        if (mFecha == null) {
            JOptionPane.showMessageDialog(null, "INGRESA DATOS");
            return;
        }
        
        long fecha = mFecha.getTime();

        Date fecha_sql = new Date(fecha);

        String fecha_Final = fecha_sql.toString();
//        JOptionPane.showMessageDialog(null, ));

        String[] partes = fecha_Final.split("-");

        int anio = Integer.parseInt(partes[0]);
        int mes = Integer.parseInt(partes[1]);
        int dia = Integer.parseInt(partes[2]);
        
        

        int indiceMesa = -1;
        if (M1.isSelected()) {
            indiceMesa = 1;
            M1.setEnabled(false);
        }
        if (M2.isSelected()) {
            indiceMesa = 2;
            M2.setEnabled(false);

        }
        if (M3.isSelected()) {
            indiceMesa = 3;
            M3.setEnabled(false);

        }
        if (M4.isSelected()) {
            indiceMesa = 4;
            M4.setEnabled(false);
        }

        Reservacion nuevo = new Reservacion(clienteActual.getId(), Date.valueOf(fecha_Final), indiceMesa, persona.getText(), dni.getText(), Integer.parseInt(cantPersonas.getValue().toString()), comentario.getText());
        conexionAReservacion.insertar(nuevo);
        JOptionPane.showMessageDialog(null, "RESERVA GENERADA");
        buttonGroup1.clearSelection();
        ActualizarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed

    void ActualizarTabla() {
        ReservacionDAO conexionAReservacion = new ReservacionDAO();
        List<Reservacion> lista_Reservaciones = conexionAReservacion.mostrar();
        ClienteDAO obtenerConexionCliente = new ClienteDAO();
        List<Cliente> lista_clientes = obtenerConexionCliente.mostrar();

        modelo = (DefaultTableModel) this.tabla.getModel();

        modelo.setRowCount(0);
        for (Reservacion rev : lista_Reservaciones) {
            if (rev.getIdCliente() == clienteActual.getId()) {
                Object[] datos = new Object[]{clienteActual.getNombre(), clienteActual.getTelefono(), rev.getFecha(), rev.getMesa(), rev.getPersona(), rev.getDNI(), rev.getCantidadPersonas(), rev.getComentario(), rev.getIdReservacion()};
                modelo.addRow(datos);
            }
        }

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        ReservacionDAO conexionAReservacion = new ReservacionDAO();
        if (id_eliminar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "INGRESA ID DE RESERVA A ELIMINAR");
            return;
        }

        conexionAReservacion.eliminar(Integer.parseInt(id_eliminar.getText()));
        ActualizarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Calendario;
    private javax.swing.JRadioButton M1;
    private javax.swing.JRadioButton M2;
    private javax.swing.JRadioButton M3;
    private javax.swing.JRadioButton M4;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JSpinner cantPersonas;
    private javax.swing.JTextArea comentario;
    private javax.swing.JTextField dni;
    private javax.swing.JTextField id_eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JTextField persona;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
