/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Datos.AlumnoDAO;
import Objetos.Alumno;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexsantiago
 */
public class PanelPersona extends javax.swing.JPanel {

    /**
     * Creates new form Persona
     */
    DefaultTableModel modeloPersona;
    AlumnoDAO conexionPersona;
    public PanelPersona() {
        initComponents();
        conexionPersona = new AlumnoDAO();
        
        modeloPersona = (DefaultTableModel) tabla.getModel();
        
        Object datos[] = new Object[3];
        
        modeloPersona.setRowCount(0);
        
        for (Alumno cliente : conexionPersona.mostrar()) {
            datos[0] = cliente.getNombre();
            datos[1] = cliente.getApellido();
            datos[2] = cliente.getcodAlumno();
            modeloPersona.addRow(datos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_limpiar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(586, 377));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_limpiar.setBackground(new java.awt.Color(255, 255, 255));
        btn_limpiar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        btn_limpiar.setToolTipText("");
        btn_limpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre");
        btn_limpiar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));
        btn_limpiar.add(tNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, -1));

        jLabel3.setText("Apellido");
        btn_limpiar.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 60, -1));
        btn_limpiar.add(tApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, -1));

        jLabel4.setText("Codigo");
        btn_limpiar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 60, -1));
        btn_limpiar.add(tDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 160, -1));

        btnLimpiar.setBackground(new java.awt.Color(255, 204, 204));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorderPainted(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        btn_limpiar.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, -1));

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setText("Registrar");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        btn_limpiar.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 400, 190));

        tabla.setBackground(new java.awt.Color(255, 102, 102));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Codigo"
            }
        ));
        tabla.setGridColor(new java.awt.Color(255, 255, 255));
        tabla.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(tabla);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 580, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/alexsantiago/NetBeansProjects/ProyectoBiblioteca/src/main/java/img/personitas.png")); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("REGISTRO DE ALUMNO");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String nombre, codigo, apellido;
        nombre = this.tNombre.getText();
        codigo = this.tDNI.getText();
        apellido = this.tApellido.getText();

        if (nombre.isBlank() || codigo.isBlank() || apellido.isBlank()) {
            JOptionPane.showMessageDialog(null, "EXISTEN CAMPOS VACIOS","ERROR",2 );
            return;
        }
        
        if(codigo.length() != 9){
            JOptionPane.showMessageDialog(null, "Codigo debe tener 9 digitos","ERROR",2);
            return;
        }

        conexionPersona.insertar(new Alumno(nombre,apellido,codigo));

        JOptionPane.showMessageDialog(null, "Alumno Guardado Correctamente");

        Object datos[] = new Object[3];

        modeloPersona.setRowCount(0);

        for (Alumno cliente : conexionPersona.mostrar()) {
            datos[0] = cliente.getNombre();
            datos[1] = cliente.getApellido();
            datos[2] = cliente.getcodAlumno();
            modeloPersona.addRow(datos);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.tApellido.setText("");
        this.tNombre.setText("");
        this.tDNI.setText("");
        this.tNombre.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel btn_limpiar;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTextField tNombre;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
