/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaces;

import Datos.HistorialClinicoDAO;
import Datos.MedicoDAO;
import Datos.PacienteDAO;
import Objetos.HistorialClinico;
import Objetos.Medico;
import Objetos.Paciente;
import javax.swing.table.DefaultTableModel;

public class PanelHistorial extends javax.swing.JPanel {

    HistorialClinicoDAO conexionHistorial;
    MedicoDAO conexionMedico;
    PacienteDAO conexionPaciente;
    
    
    DefaultTableModel modeloMedico;
    
    
    
    public PanelHistorial() {
        initComponents();
        conexionHistorial = new HistorialClinicoDAO();
        conexionMedico = new MedicoDAO();
        conexionPaciente = new PacienteDAO();
       
        //aca solo INICIALIZA EL COMBO BOX DE PACIENTES
        for(Paciente paciente : conexionPaciente.mostrar())
        {
            String nombre_dni = paciente.getNombre() + " " + paciente.getApellido() + " " + paciente.getDni();
            cb_lista_pacientes.addItem(nombre_dni);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabel = new javax.swing.JLabel();
        tDNI = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lbDNI = new javax.swing.JLabel();
        lbNombreApellido = new javax.swing.JLabel();
        cb_lista_pacientes = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jlabel.setText("Dni Paciente");

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        btnBuscar.setBackground(new java.awt.Color(153, 153, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnTodos.setBackground(new java.awt.Color(153, 153, 255));
        btnTodos.setText("Mostrar Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addComponent(btnTodos)
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnTodos))
                .addContainerGap())
        );

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Doctor", "Consulta", "Diagnostico"
            }
        ));
        tabla.setGridColor(new java.awt.Color(153, 153, 255));
        tabla.setSelectionBackground(new java.awt.Color(204, 204, 255));
        tabla.setShowGrid(true);
        tabla.getTableHeader().setResizingAllowed(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(80);
            tabla.getColumnModel().getColumn(0).setMaxWidth(80);
            tabla.getColumnModel().getColumn(1).setPreferredWidth(130);
            tabla.getColumnModel().getColumn(1).setMaxWidth(130);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(120);
            tabla.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        lbDNI.setText("DNI");

        lbNombreApellido.setText("nombre");

        cb_lista_pacientes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_lista_pacientesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_lista_pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNombreApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_lista_pacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String dni = tDNI.getText();
        //CREANDO LOS LABELS
        Paciente paciente = conexionPaciente.obtenerPacienteByDni(dni);
        lbDNI.setText("DNI : " + paciente.getDni());
        lbNombreApellido.setText("Informacion : " + paciente.getNombre() + " " + paciente.getApellido());
        
        
        //AGREGANDO A LA TABLA DE HISTORIAL CLINICO SOLO LOS QUE TENGAN EL ID DEL HISTORIAL
        modeloMedico = (DefaultTableModel) tabla.getModel();

        Object datos[] = new Object[4];

        modeloMedico.setRowCount(0);
        
        for (HistorialClinico historial : conexionHistorial.mostrar()) {
            
            if(paciente.getId() != historial.getPaciente_id())// SI PACIENTE ES DIFERENTE AL ID DEL DNI BUSCADO
                continue;//ENTONCES CONTINUARA HACIA ARRIBA O SEA SE SALTARA LA PARTE DE ABAJO, NO LE INTERESA LO DE ABAJO SI NO ENCUENTRO EL ID
            
            
            Medico medico = conexionMedico.obtenerMedicoByID(historial.getMedico_id());
            datos[0] = medico.getDni();
            datos[1] = medico.getNombre() + " " + medico.getApellido();
            datos[2] = historial.getFecha_consulta();
            datos[3] = historial.getDiagnostico();
            modeloMedico.addRow(datos);
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        
        //ACTUALIZANDO LA TABLA
        modeloMedico = (DefaultTableModel) tabla.getModel();

        Object datos[] = new Object[4];

        modeloMedico.setRowCount(0);
        
        for (HistorialClinico historial : conexionHistorial.mostrar()) {
            
            Medico medico = conexionMedico.obtenerMedicoByID(historial.getMedico_id());
            datos[0] = medico.getDni();
            datos[1] = medico.getNombre() + " " + medico.getApellido();
            datos[2] = historial.getFecha_consulta();
            datos[3] = historial.getDiagnostico();
            modeloMedico.addRow(datos);
        }
    }//GEN-LAST:event_btnTodosActionPerformed

    private void cb_lista_pacientesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_lista_pacientesItemStateChanged

        String str = cb_lista_pacientes.getSelectedItem().toString();

        String[]cadenas = str.split(" ");

        tDNI.setText(cadenas[cadenas.length-1]);

    }//GEN-LAST:event_cb_lista_pacientesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JComboBox<String> cb_lista_pacientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lbDNI;
    private javax.swing.JLabel lbNombreApellido;
    private javax.swing.JTextField tDNI;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
